name: bucket

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup bucket
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Test bucket
      run: dotnet test -c Release -s src/settings.runsettings /p:CollectCoverage=true /p:CoverletOutputFormat=teamcity /p:Exclude=[*.Tests]* /p:Threshold=60 /p:ThresholdType=line
